{
    "success": true,
    "message": "Paginated lottery draws retrieved successfully",
    "data": [
        {
            "id": "d749e095-2984-4856-a72e-d57533972700",
            "externalId": null,
            "drawDate": "2026-05- :30:00.000Z",
            "isClosed": false,
            "results": null,
            "status": "UPCOMING",
            "expireDate": "2026-05-14T17:34:00.000Z",
            "createdAt": "2026-05-12T08:25:17.050Z",
            "customerId": null
        },
        {
            "id": "168313d0-c6ed-4b54-b54d-8f534b1b6188",
            "externalId": "16052569",
            "drawDate": "2026-05-16T09:00:00.000Z",
            "isClosed": true,
            "results": {
                "date": "16 พฤษภาคม 2569",
                "prizes": [
                    {
                        "id": "prizeFirst",
                        "name": "รางวัลที่ 1",
                        "amount": 1,
                        "number": [
                            "xxxxxx"
                        ],
                        "reward": "6000000"
                    },
                    {
                        "id": "prizeFirstNear",
                        "name": "รางวัลข้างเคียงรางวัลที่ 1",
                        "amount": 2,
                        "number": [
                            "xxxxxx",
                            "xxxxxx"
                        ],
                        "reward": "100000"
                    },
                    {
                        "id": "prizeSecond",
                        "name": "รางวัลที่ 2",
                        "amount": 5,
                        "number": [
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx"
                        ],
                        "reward": "200000"
                    },
                    {
                        "id": "prizeThird",
                        "name": "รางวัลที่ 3",
                        "amount": 10,
                        "number": [
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx"
                        ],
                        "reward": "80000"
                    },
                    {
                        "id": "prizeForth",
                        "name": "รางวัลที่ 4",
                        "amount": 50,
                        "number": [
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx"
                        ],
                        "reward": "40000"
                    },
                    {
                        "id": "prizeFifth",
                        "name": "รางวัลที่ 5",
                        "amount": 100,
                        "number": [
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx",
                            "xxxxxx"
                        ],
                        "reward": "20000"
                    }
                ],
                "endpoint": "https://news.sanook.com/lotto/check/16052569",
                "runningNumbers": [
                    {
                        "id": "runningNumberFrontThree",
                        "name": "รางวัลเลขหน้า 3 ตัว",
                        "amount": 2,
                        "number": [
                            "xxx",
                            "xxx"
                        ],
                        "reward": "4000"
                    },
                    {
                        "id": "runningNumberBackThree",
                        "name": "รางวัลเลขท้าย 3 ตัว",
                        "amount": 2,
                        "number": [
                            "xxx",
                            "xxx"
                        ],
                        "reward": "4000"
                    },
                    {
                        "id": "runningNumberBackTwo",
                        "name": "รางวัลเลขท้าย 2 ตัว",
                        "amount": 1,
                        "number": [
                            "xx"
                        ],
                        "reward": "2000"
                    }
                ]
            },
            "status": "FINISHED",
            "expireDate": "2026-07-15T09:00:00.000Z",
            "createdAt": "2026-05-11T08:55:02.832Z",
            "customerId": null
        }
    ],
    "meta": {
        "total": 2,
        "page": 1,
        "limit": 10,
        "totalPages": 1
    }
}